@startuml 


actor "Поставщик" as seller

boundary "Окно заказов" as list_of_orders

control "Запросить отправленные заказы из базы данных" as give_me_orders

control "Перейти к заказу" as to_order_list

boundary "Окно выбранного заказа" as selected_order

control "Запросить детали заказа из базы данных" as give_me_order_details




control "Одобрить заказ" as accept_order

control "Отменить заказ" as cansel_order

entity "Фасад БД" as facade_bd

'entity


seller--list_of_orders

list_of_orders-- give_me_orders 


list_of_orders--to_order_list

to_order_list--selected_order

selected_order--give_me_order_details

selected_order--accept_order
selected_order--cansel_order

'give_me_order_details--cansel_order
give_me_orders--facade_bd
give_me_order_details--facade_bd
accept_order--facade_bd
cansel_order--facade_bd



@enduml