@startuml


actor "Aдминистратор" as admin

boundary "Окно каталога деталей" as admin_order_list

control "Добавить товар в заказ" as add_to_order 

control "Выбрать товар" as select_item

control "Загрузить доступные для покупки товары из базы данных" as give_me_details 

boundary "Всплывающее окно заказа" as admin_selected_order

control "Выбрать количество товара" as choose_count

control "Создать заказ соответсвующему поставщику" as get_order

entity "Фасад БД" as facade_bd

admin -- admin_order_list

admin_order_list -- select_item

admin_order_list -- give_me_details

give_me_details--facade_bd



'admin_order_list -- give_me_details





admin_order_list--add_to_order

add_to_order -- admin_selected_order

admin_selected_order--choose_count

choose_count--get_order

get_order--facade_bd

@enduml