@startuml Администратор_мазагина

left to right direction 

Поставщик --> (Изменить товар на складе)
Поставщик --> (Добавить новый товар)
Поставщик --> (Обработать заявку администратора магазина)

Администратор_магазина --> (Просмотреть товары)
Администратор_магазина --> (Добавить товар в заказ)
Администратор_магазина --> (Удалить товар из заказа)
Администратор_магазина --> (Отправить заказ поставщику)










@enduml