@startuml old_diam

|#Pink|Адм|Администратор магазина
|#LightGreen|Кур|Курьер
|#LightBlue|Пост|Поставщик


|Адм|
start
:Создание заявки в письменном виде;
:Передача заявки лично в руки курьеру поставщика;


|Кур|
:Забирает заявку и уходит;  
:Передача заявки поставщику;
if (Администратор магазина захотел изменить заказ ?) is (Да) then
|Адм|
:Администратор магазина ждёт следующего курьера;

else(Нет)
endif

|Пост|

:Переписывание информации с бумажной заявки в базу данных;
:Сбор заказа;
:Передача заказа курьеру;

|Кур|
:На следующий день забирает заказ и отвозит его администратору;

|Адм|
:Забирает заказ;
stop
@enduml
