@startuml old_diam

|#Pink|Адм|Администратор_магазина
|#LightBlue|Пост|Поставщик
|#LightGreen|Кур|Курьер

|Адм|
start
:Создание заявки в письменном виде;
:Передача заявки лично в руки курьеру поставщика;


|Пост|
:Забирает заявку;
if (Администратор магазина захотел изменить заказ ?) is (Да) then
|Адм|
:Администратор магазина ждёт следующего курьера;

else(Нет)
endif



|Кур|
stop
@enduml
