@startuml 


actor "Поставщик" as seller

boundary "Окно каталога деталей" as list_of_details

control "Перейти к заказу" as to_order_list

boundary "Окно выбранного заказа" as selected_order

control "Одобрить заказ" as accept_order

control "Отменить заказ" as cansel_order

entity "Фасад БД" as facade_bd

'entity


seller--list_of_details

list_of_details-->to_order_list

to_order_list-->selected_order

selected_order-->accept_order

selected_order-->cansel_order

accept_order-->facade_bd
cansel_order-->facade_bd



@enduml