@startuml states
left to right direction

[*] --> login

state login as "Вход в систему" {
  login : <img https://img.plantuml.biz/plantuml/png/VOun3e9044NxESM46m05sd4FGa6Y7R6GxSH4JBGMAXeumqOXheboXZytOlO2LfFy_rx-f9KfZgOgIiFev8O54z69cD5ZmC0OvO8NB7vmUCFANQ_ZceDm4oTXj4q23pymAJTByqT0YqKx9uskF64vHklbJ9KhlfXLiPpN6Je5FfgvdCv4wVwmym-k>
}

login --> admin : Вход выполнен (Администратор магазина)
login --> seller : Вход выполнен (Поставщик)

state admin as "Рабочий стол администратора магазина" {
  state admin_item_list as "Список товаров" {
    admin_item_list : <img https://img.plantuml.biz/plantuml/png/JL8xJiDG4EnpYfLeGV87EeGGXw11AK3G8Gf8Hv12KW0AA7nI8CHNGhGOWsN7nkOAirVW11o1sMSNVfRUsklTsTdPNJteRUxt3ZPtUu8N_23JOrJ8HOSqCI8TcEqSTeIdlkriu5h7c34g4sH8XMbCvNU2Rnrt-njuOgAXvVBtDBqmpoiZ2ptNeGww3kd8tSjRAxXZfI4Y54pw57mXQJuJpEhISowEeAvAX5ZF29TBt_aVw4cDBqfwayPxgGDZY5n7A6hN6n5BHFscQiKIcPwmdA76g5mnFDeZUCUdZdH0D4oRNamNQlBDp9H05MQo7eHhmXZFztspllSxB9trf8PxONSJb89Rb2OH0KhUfxmBon0yarPAfYLoHD88cJivAjAhfSsSjz39l71IXf9GgL8dEX4dbSsBhtU1ln3uZa4Gq0GDeILF6a9NRh3KmOJXHDYPausKo477rd5hMi9-8mOLreNDNN13olSBlbK9myNGJ5Cbz5gpRM_CbCrysEIi4JrlhPWW5Z8mOPq8EkhsRSNuxzGMB7NwnKQolJYTeyxgpjwsBUy_>
  }
  state admin_zayav_list as "Ваши заявки" {
    admin_zayav_list: <img https://img.plantuml.biz/plantuml/png/TLB1Ji905Bpp5Pju9osLcp7yX-60qPln8Dme2RGN3KQY8Uf18No15MqeXS8lpFi5lyJPjn08qMwoJRSpy-RDsrgprRXfDHjNBOC9riYaXnLoWnaI6M1gFqhjak5pXYUaqaKXiKHoBpqP68lCYOoGO47ibyG6tuIvWnJpkd9Fpa__bxU0zf5YnbXHrvAdSeSCUQZ7GrV2A7l60WaAQWrsEZaoux0JYwJ1M7gRan4-AKOS-H9ZoPKeqrgtRtL069V1Xsr2kc6bMlQgvOhdLIc3TwI6tYAicG3TQNC5TK93YEVzH8LnCezum_C1UxXh2mlwPJuQNsZyeEfNI7RSYNPJ6BmovSYbpVsM--90SlI74pzmJhP64kKdx7bXvsL3OXkKooZV3tr_N_15nLYI_vqWJuFWEF2tYXtTtRXqTxTYh3uvQZhEz4PCfS_8kpgbWXERC-tDbD9wICg8qALMoUnLEc0m_eUzoKfSto_VATKkho_iZVq5>
  }
  
}

@enduml