@startsalt Отправление заявки
{
    [Вернуться к каталогу товаров]
    <b>Ваш заказ у поставщика ООО Ягур
    {#<b>Название | <b>Артикул| <b>Цена| <b>Количество
    Диск тормозной V23B  | 0111  | 10₽ | 100 
    Резинка стеклоочистителя, передняя левая К21-21 | 1022 | 20₽ | 50  
    Фильтр масляный ГРМ-11 | 3343 | 30₽ | 30
    }
    {
        [Удалить товар из заявки]|  [Отправить заявку]
    }
    
}
@endsalt