@startsalt Список заявок
{
    [Вернуться к каталогу деталей]
    <b>Список заявок
    {# <b>Поставщик| <b>Дата создания заявки | <b>Статус | <b>Общая сумма заказа
    ООО Ягур|25.05.2005 | Создаётся | 20000₽ 
    Саян Интернешнл|25.05.2005 | Выполняется | 13000₽
    Барнаульские шины|11.05.2005 | Совершенно  | 33431₽
    }
    {
        [Перейти к выбранной зявке]| [Отменить выбранную заявку]
    }
    
}
@endsalt