@startsalt Список товаров
{
    {
        [Выйти из системы]|[Фильтр]
    }
    <b>Каталог деталей
    {# <b>Поставщик | <b>Название | <b>Артикул| <b>Цена| <b>Количество
    ООО Ягур | Диск тормозной V23B  | 0111  | 10₽ | 100 
    Саян Интернешнл  |  Резинка стеклоочистителя, передняя левая К21-21 | 1022 | 20₽ | 50  
    Барнаульские шины | Фильтр масляный ГРМ-11 | 3343 | 30₽ | 30
    }
    {
        [Добавить выбранный товар в заказ]| [Ваши заказы]
    }
    
}
@endsalt