@startsalt Список заявок
{
    [Вернуться к каталогу деталей]
    [X]Показывать только незавершённые заказы
    <b>Список заказов
    {# <b>Поставщик| <b>Дата создания заказа | <b>Статус | <b>Общая сумма заказа
    ООО Ягур|25.05.2005 | Не отправлена | 20000₽ 
    БМЖ|25.05.2005 | Доставляется | 13512₽
    Саян Интернешнл|25.05.2005 | Оправлена | 13000₽
    Барнаульские шины|11.05.2005 | Завершена  | 33431₽
    }
    
    {
        [Перейти к выбранному заказу]
    }
    
}
@endsalt