@startsalt Фильтр
{
    <b>Фильтр
    {#
    
        <b>Поставщик|//Впишите название поставщика//
        <b>Название |//Впишите название детали//
        <b>Цена|//Впишите цену меньше которой вы ищите//
        <b>Артикул|//Впишите артикул//
    }
    [Отфильтровать товары]
    
    
}
@endsalt