@startsalt Отправление заявки
{
    [Вернуться к просмотру товаров]
    <b>Ваши заявки
    {#<b>Номер заявки|<b>Юр. лицо| <b>Общая сумма заказ| <b>Адрес
    1|Детали от Семёныча|10000|Волочаевская 44
    2|Детали|15000|Волочаевская Октября 78
    3|Стальные шестерни|20000|Красной Армии 3
    }
    {
        [Перейти к выбранной заявке]
    }
    
}
@endsalt