@startsalt Отправление заявки
{
    [Вернуться к просмотру товаров]
    <b>Заявка Детали от Семёныча - Волочаевская 44 - "Ждёт ответа"
    {#<b>Название|<b>Артикул| <b>Цена| <b>Количество
    Диск тормозной V23|5512|1010|10
    Колодки тормазные форд фокус|1113|2050|15

    
    }
    {
        [Ответить на заявку]|[Отклонить заявку]
    }
    
}
@endsalt