@startsalt Список товаров
{
    {
        [Вернуться к просмотру товаров]|
    }
    <b>Информация о товаре
    {#<b>Название |Впишите название
        <b>Цена|//Впишите цену//
        <b>Артикул|//Впишите артикул//
        <b>Количество|//Впишите количество//
    }
    [Добавить товар]
    
    
}
@endsalt