@startsalt Отправление заявки
{
    [Вернуться к вашим заказам]
    <b> Ваш заказ у поставщика ООО Ягур
    {#<b>Название детали|<b>Артикул| <b>Цена| <b>Количество
    Диск тормозной V23|5512|1010|10
    Колодки тормазные форд фокус|1113|2050|15

    
    }
    {
        [Удалить выбранный товар из заказа]
        [Отправить заказ поставщику]
    }
    
}
@endsalt