@startsalt Отправление заявки
{
    [Вернуться к заявкам]
    <b> Ваш заказ у поставщика ООО Ягур
    {#<b>Название|<b>Артикул| <b>Цена| <b>Количество
    Диск тормозной V23|5512|1010|10
    Колодки тормазные форд фокус|1113|2050|15

    
    }
    {
        [Удалить товар из заявки]|[Отправить заявку]
    }
    
}
@endsalt