@startuml Администратор_мазагина

Администратор_магазина --> (Просмотреть товары)
Администратор_магазина --> (Добавить товар в корзину)
Администратор_магазина --> (Изменить заказ)
Администратор_магазина --> (Отправить заказ поставщику)



@enduml