@startuml Диаграмма классов
 
class FacadeDB{
  --
  + add(Object object) => Object
}
 
interface IUserDB {
  + get_users(  ) => List<Item>
  + save_сhanges()
  + cansel_сhanges()
}
 
interface IItemDB {
  
  + get_items() => List<Item>
  + save_сhanges()
  + cansel_сhanges()
}
 
interface IOrderDB {

  + get_orders() => List<Item>
  + save_сhanges()
  + cansel_сhanges()

}
 
FacadeDB ..|> IUserDB
FacadeDB ..|> IItemDB
FacadeDB ..|> IOrderDB
 
IUserDB <--o User

IUserDB <--o Item
IItemDB <--o Item
IOrderDB <--o Order
 



class User {
  * id: TEXT
  --
  + status: UserStatus
  + login: TEXT
  + password_hash: TEXT
  + INN: INT
  + legal_entity: TEXT
  + adress: TEXT
  + registred_in: DATETIME
}

enum UserStatus {
  ADMIN
  SELLER
}
 
User *- UserStatus
 
 

 
class Item {
  * id: TEXT
  --
  + name: TEXT
  + article: INT
  + price: NUMERIC
  + created_at: DATETIME
}
 
class Order {
  * id: TEXT
  --
  + user_id: TEXT
  + total_price: NUMERIC
  + final_price: NUMERIC
  + status: OrderStatus
  + created_at: DATETIME
}
 
enum OrderStatus {
  WAITING
  COMPLITING
  COMPLETED
  CANCELLED
}
 
Order *- OrderStatus
 
' WINDOWS
 
package "Item Windows" {
SellerWindowItemList o--> IItemDB
AdminWindowItemList o--> IItemDB
}
package "Order Windows" {
AdminWindowOrder o--> IOrderDB
SellerWindowOrder o--> IOrderDB
}

package "Login Windows" {
AdminWindowLogin o--> IUserDB
SellerWindowLogin o--> IUserDB
}



package "OrderList Windows" {
AdminWindowOrderList o--> IOrderDB
SellerWindowOrderList o--> IOrderDB
}


 
@enduml
 