@startsalt Список товаров
{
    {
        [Сохранить изменения]|
    }
    <b>Информация о товаре
    {#<b>Название |Тормозной диск А2-Б2
        <b>Цена|1600₽
        <b>Артикул|0123
        <b>Количество|10

      
    
    }
    
    
}
@endsalt